import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  ar: {
    brandName: 'ميزون دي روز',
    brandTagline: 'زهور وتحف فاخرة في الرياض',
    brandSub: 'المتجر الفاخر لتنسيق الزهور والهدايا الراقية',
    navHome: 'الرئيسية',
    navCatalog: 'مجموعتنا الفاخرة',
    navBuilder: 'المنسق التفاعلي',
    navExperience: 'تجربة ميزون',
    navContact: 'تواصل معنا',
    orderNow: 'اطلب الآن',
    quickOrder: 'طلب سريع',
    addToCart: 'إضافة للسلة',
    viewCart: 'عرض الحقيبة',
    checkoutWhatsApp: 'تأكيد الطلب عبر الواتساب',
    sar: 'ر.س',
    heroTag: 'بوتيك الزهور الراقية في الرياض 🇸🇦',
    heroTitle: 'فخامة المشاعر في كل تفصيلة',
    heroDesc: 'نصنع تحفاً خالدة من الزهور الطبيعية النادرة وأرقى الهدايا المصممة خصيصاً لأصحاب الذوق الرفيع. خدمة توصيل VIP فائقة العناية داخل مدينة الرياض.',
    heroCtaBuilder: 'صمم هديتك الخاصة (المنسق التفاعلي)',
    heroCtaCatalog: 'استكشف التشكيلة الحصرية',
    badgeDelivery: 'توصيل مبرد VIP خلال ساعتين في الرياض',
    badgeQuality: 'أزهار طبيعية فاخرة قطاف يومي طازج',
    badgeLuxury: 'علب مخملية وصواني رخامية أصلية',
    catalogHeading: 'التشكيلة الراقية الحصرية',
    catalogSubheading: 'روائع فنية مختارة بعناية للمناسبات الملكية واللحظات الخاصة',
    catAll: 'الكل',
    catRoses: 'الورد الملكي',
    catVases: 'فازات الرخام والكريستال',
    catVIP: 'باقات كبار الشخصيات VIP',
    catOccasions: 'أفراح ومناسبات خاصة',
    builderTitle: 'المنسق التفاعلي للهدايا الفاخرة',
    builderSubtitle: 'صمم تحفتك الاستثنائية خطوة بخطوة واختر التنسيق، الأزهار، الإضافات، والكارت المكتوب بخط اليد',
    step1Title: '١. القاعدة والتنسيق',
    step1Desc: 'اختر الأساس الفاخر لهديتك',
    step2Title: '٢. نوع ولون الورد',
    step2Desc: 'اختر باقة الزهور المفضلة',
    step3Title: '٣. إضافات الذوق الرفيع',
    step3Desc: 'عطور، شوكولاتة بلجيكية فاخرة، كيك وتحف',
    step4Title: '٤. كارت الإهداء والخط الملكي',
    step4Desc: 'معاينة حية لرسالتك بخط ديواني فاخر',
    selectedBase: 'القاعدة المختارة',
    selectedFlower: 'الزهور المختارة',
    selectedAddons: 'الإضافات المختارة',
    totalPrice: 'المجموع الإجمالي',
    deliveryIncluded: 'شامل التنسيق الفاخر والتغليف الملكي',
    resetBuilder: 'إعادة البدء',
    previewCardText: 'نص رسالة الإهداء المكتوبة بخط اليد',
    cardPlaceholder: 'اكتب هنا ما يمليه عليك قلبك لمن تحب...',
    fontStyle: 'أسلوب الخط الملكي',
    fontStyleDiwani: 'خط عربي كلاسيكي أصيل',
    fontStyleRuqah: 'خط رقعة عصري مذهب',
    cardAuthor: 'اسم المرسل (على الكارت)',
    cardAuthorPlaceholder: 'مثال: محبك للأبد / فهد',
    modalTitle: 'تأكيد تفاصيل الطلب والتوصيل في الرياض',
    modalSubtitle: 'سيتم تحويل طلبك مباشرة مع كافة التفاصيل إلى فريق ميزون دي روز عبر الواتساب',
    senderName: 'اسم المرسل',
    senderNamePlaceholder: 'الاسم الكامل للمرسل',
    recipientName: 'اسم المستلم',
    recipientNamePlaceholder: 'اسم من ستهديه هذه التحفة',
    recipientPhone: 'رقم جوال المستلم',
    recipientPhonePlaceholder: '05xxxxxxxx',
    cityDistrict: 'المدينة والحي (داخل الرياض)',
    cityDistrictPlaceholder: 'مثال: الرياض - حي الملقا / حطين / النرجس',
    detailedAddress: 'العنوان التفصيلي أو معلم بارز',
    detailedAddressPlaceholder: 'الشارع، رقم المبنى، فيلا رقم...',
    deliveryDate: 'تاريخ التوصيل المطلوب',
    deliveryTimeSlot: 'الفترة الزمنية المفضلة للتوصيل',
    timeSlot1: 'صباحية (١٠:٠٠ ص - ٢:٠٠ م)',
    timeSlot2: 'مسائية أولى (٣:٠٠ م - ٧:٠٠ م)',
    timeSlot3: 'سهرة مسائية VIP (٨:٠٠ م - ١٢:٠٠ منتصف الليل)',
    timeSlotNow: 'توصيل فوري VIP عاجل (خلال ساعتين)',
    cardMessageLabel: 'نص رسالة كارت الإهداء',
    cardMessagePlaceholder: 'الرسالة التي ستكتب بالخط الملكي وتوضع مع الهدية...',
    specialNotes: 'ملاحظات وتوجيهات خاصة للسائق والتسليم',
    specialNotesPlaceholder: 'مثال: هدية مفاجأة بدون ذكر اسم المرسل / الرنين مرتين فقط...',
    confirmWhatsAppBtn: 'إرسال الطلب واعتماده عبر الواتساب',
    cartEmpty: 'حقيبة التسوق فارغة حالياً',
    cartEmptySub: 'استمتع باكتشاف تصاميمنا الفاخرة أو اصنع هديتك الخاصة',
    cartItemsCount: 'عناصر بالحقيبة',
    checkoutNow: 'إتمام الطلب',
    remove: 'حذف',
    qty: 'الكمية',
    featuresTitle: 'لماذا يختار النخبة ميزون دي روز؟',
    feature1Head: 'زهور هولندية وإكوادورية طازجة',
    feature1Desc: 'نستورد يومياً أرقى أصناف الورد الطبيعي لضمان بقائها نضرة ومفعمة بالحياة لأطول فترة.',
    feature2Head: 'أسطول توصيل مبرد وراقي',
    feature2Desc: 'سيارات مجهزة بأنظمة ضبط الحرارة وسائقون مدربون على أعلى بروتوكولات تسليم الهدايا الفاخرة.',
    feature3Head: 'كروت إهداء بخط يد ملكي',
    feature3Desc: 'يقوم خطاطونا المحترفون بكتابة رسائلكم بماء الذهب والأحبار الملكية على ورق قطني فاخر.',
    feature4Head: 'شوكولاتة وعطور نيش حصرية',
    feature4Desc: 'نشارك أرقى دور العطور والشوكولاتة السويسرية والبلجيكية لتقديم تجربة إهداء لا تُنسى.',
    testimonialsHeading: 'آراء ضيوفنا الكرام',
    vipSupport: 'خدمة كبار الشخصيات على مدار الساعة',
    riyadhCoverage: 'تغطية شاملة لكافة أحياء الرياض والدرعية',
    footerAbout: 'ميزون دي روز هي دار الفخامة الرائدة لتنسيق الزهور الطبيعية والهدايا الحصرية في العاصمة الرياض، المملكة العربية السعودية.',
    footerQuickLinks: 'روابط سريعة',
    footerWorkingHours: 'ساعات العمل والإرسال',
    footerHoursText: 'يومياً من ٩:٠٠ صباحاً حتى ١٢:٠٠ منتصف الليل (خدمة الاستقبال والتوصيل)',
    footerContact: 'العنوان والتواصل',
    footerAddress: 'طريق الأمير تركي بن عبدالعزيز الأول، حطين، الرياض',
    copyright: '© 2026 ميزون دي روز - جميع الحقوق محفوظة لعلامة الفخامة.',
    deliveryFeeFree: 'شامل التوصيل المجاني الراقي',
    viewDetails: 'عرض التفاصيل',
    close: 'إغلاق',
    stepNext: 'الانتقال للخطوة التالية',
    stepBack: 'الرجوع للخطوة السابقة',
    customBoxCompleted: 'اكتملت تحفتك الفاخرة!',
    customBoxReadyDesc: 'تم حفظ كافة خياراتك، يمكنك الآن نقلها إلى الواتساب للاعتماد الفوري.',
  },
  en: {
    brandName: 'MAISON DE ROSES',
    brandTagline: 'Haute Floral & Luxury Gifting Riyadh',
    brandSub: 'The Premier Luxury Florist & Gift Atelier in Riyadh',
    navHome: 'Home',
    navCatalog: 'Collections',
    navBuilder: 'Gift Box Builder',
    navExperience: 'The Experience',
    navContact: 'Contact',
    orderNow: 'Order Now',
    quickOrder: 'Quick Order',
    addToCart: 'Add to Bag',
    viewCart: 'Shopping Bag',
    checkoutWhatsApp: 'Confirm Order via WhatsApp',
    sar: 'SAR',
    heroTag: 'Haute Florist Atelier in Riyadh 🇸🇦',
    heroTitle: 'Luxury Crafted in Every Petal',
    heroDesc: 'Curating timeless bespoke floral arrangements and refined luxury gifts for those with discerning taste. Discreet, white-glove climate-controlled VIP delivery across Riyadh.',
    heroCtaBuilder: 'Design Bespoke Gift Box (Interactive)',
    heroCtaCatalog: 'Explore Exclusive Collections',
    badgeDelivery: 'VIP 2-Hour Chilled Delivery in Riyadh',
    badgeQuality: 'Daily Hand-Picked Grade-A Fresh Blooms',
    badgeLuxury: 'French Velvet Boxes & Italian Marble Vases',
    catalogHeading: 'Exclusive Signature Collections',
    catalogSubheading: 'Artisanal arrangements hand-crafted for celebratory milestones and royal moments',
    catAll: 'All',
    catRoses: 'Imperial Roses',
    catVases: 'Marble & Crystal Vases',
    catVIP: 'VIP Executive Hampers',
    catOccasions: 'Weddings & Celebrations',
    builderTitle: 'Interactive Custom Gift Box Builder',
    builderSubtitle: 'Curate your bespoke masterpiece step-by-step: select luxury vessel, flower palette, gourmet add-ons, and handwritten royal calligraphy card.',
    step1Title: '1. Base & Vessel',
    step1Desc: 'Select the foundation for your gift',
    step2Title: '2. Flowers & Color Palette',
    step2Desc: 'Choose your signature fresh blooms',
    step3Title: '3. Haute Add-ons',
    step3Desc: 'Belgian chocolates, niche oud, artisan cakes',
    step4Title: '4. Card & Calligraphy',
    step4Desc: 'Live real-time preview of your greeting',
    selectedBase: 'Selected Base',
    selectedFlower: 'Selected Flowers',
    selectedAddons: 'Selected Add-ons',
    totalPrice: 'Total Price',
    deliveryIncluded: 'Includes luxury presentation & silk ribboning',
    resetBuilder: 'Reset Builder',
    previewCardText: 'Calligraphy Card Live Preview',
    cardPlaceholder: 'Compose your heartfelt greeting here...',
    fontStyle: 'Calligraphy Script Style',
    fontStyleDiwani: 'Classic Royal Script',
    fontStyleRuqah: 'Modern Gilded Script',
    cardAuthor: 'Sender Signature (on Card)',
    cardAuthorPlaceholder: 'e.g. Forever yours, Fahad',
    modalTitle: 'Confirm Order & Delivery Details (Riyadh)',
    modalSubtitle: 'Your tailored order will be formatted and seamlessly sent to Maison De Roses via WhatsApp',
    senderName: 'Sender Full Name',
    senderNamePlaceholder: 'Your full name',
    recipientName: 'Recipient Name',
    recipientNamePlaceholder: 'The lucky recipient’s name',
    recipientPhone: 'Recipient Mobile Number',
    recipientPhonePlaceholder: '05xxxxxxxx',
    cityDistrict: 'City & District (Riyadh)',
    cityDistrictPlaceholder: 'e.g. Riyadh - Al Malqa / Hittin / Al Narjis',
    detailedAddress: 'Detailed Address / Landmark',
    detailedAddressPlaceholder: 'Street, Villa number, landmark...',
    deliveryDate: 'Preferred Delivery Date',
    deliveryTimeSlot: 'Preferred Delivery Window',
    timeSlot1: 'Morning (10:00 AM - 2:00 PM)',
    timeSlot2: 'Afternoon (3:00 PM - 7:00 PM)',
    timeSlot3: 'Evening VIP (8:00 PM - 12:00 Midnight)',
    timeSlotNow: 'Urgent Express VIP (Within 2 Hours)',
    cardMessageLabel: 'Card Inscription / Message',
    cardMessagePlaceholder: 'Message to be written in calligraphy...',
    specialNotes: 'Special Instructions & Courier Notes',
    specialNotesPlaceholder: 'e.g. Surprise delivery without revealing sender / Ring once...',
    confirmWhatsAppBtn: 'Send Order via WhatsApp',
    cartEmpty: 'Your shopping bag is currently empty',
    cartEmptySub: 'Explore our curated collections or build a bespoke gift box',
    cartItemsCount: 'Items in Bag',
    checkoutNow: 'Checkout Now',
    remove: 'Remove',
    qty: 'Qty',
    featuresTitle: 'Why Discerning Clients Choose Us',
    feature1Head: 'Dutch & Ecuadorian Direct Imports',
    feature1Desc: 'We receive freshly cut, top-tier long-stem roses and blooms flown in daily from world-class growers.',
    feature2Head: 'Climate-Controlled VIP Fleet',
    feature2Desc: 'Temperature-monitored Mercedes Sprinter vans and uniformed concierges ensure pristine doorstep presentation.',
    feature3Head: 'Master Gilded Calligraphy',
    feature3Desc: 'In-house master calligraphers hand-inscribe your cards with gold leaf and archival ink on Italian cotton paper.',
    feature4Head: 'Artisan Chocolates & Niche Scents',
    feature4Desc: 'Exclusive partnerships with Swiss master chocolatiers and Arabian niche perfumers for uncompromised prestige.',
    testimonialsHeading: 'Client Testimonials',
    vipSupport: '24/7 Dedicated VIP Concierge',
    riyadhCoverage: 'Full coverage across Greater Riyadh & Diriyah',
    footerAbout: 'Maison De Roses is Riyadh’s premier luxury atelier for bespoke floral compositions and curated gifting.',
    footerQuickLinks: 'Quick Links',
    footerWorkingHours: 'Showroom & Delivery Hours',
    footerHoursText: 'Daily: 9:00 AM – 12:00 Midnight (VIP Concierge & Express Logistics)',
    footerContact: 'Atelier & Contact',
    footerAddress: 'Prince Turki Al-Awwal Road, Hittin District, Riyadh, Saudi Arabia',
    copyright: '© 2026 MAISON DE ROSES. All Rights Reserved.',
    deliveryFeeFree: 'Complimentary VIP Chilled Delivery Included',
    viewDetails: 'View Details',
    close: 'Close',
    stepNext: 'Next Step',
    stepBack: 'Previous Step',
    customBoxCompleted: 'Masterpiece Configured!',
    customBoxReadyDesc: 'Your selections have been curated. Confirm your order now via WhatsApp concierge.',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('luxury_lang') || 'ar'; // Default Arabic
  });

  useEffect(() => {
    const root = document.documentElement;
    root.setAttribute('lang', lang);
    root.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    localStorage.setItem('luxury_lang', lang);
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'ar' ? 'en' : 'ar'));
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['ar']?.[key] || key;
  };

  const isRTL = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
